In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("yelp_data_clean.csv")
# data.head()

In [3]:
data.shape

(4487, 9)

In [4]:
categories = ['Chinese', 'Mexican', 'Italian', 'Greek', 'French', 'Japanese', 'Thai', 'Spanish', 'Indian', 'American']
# for name in categories:
#     print(name)


In [5]:
specific_data = data.loc[data['categories']=='American']
X = specific_data[['latitude', 'longitude', 'rating']].to_numpy()
# y_rating_temp = Chinese_data['rating'].to_numpy()
y_price_temp = specific_data['price'].to_numpy()
# y_rating_temp = y_rating_temp.reshape(-1, 1)
y_price_temp = y_price_temp.reshape(-1,1)
# print(y_rating_temp.max(), y_rating_temp.min())
# print(y_price_temp.max(), y_price_temp.min())

In [6]:
X[30]

array([  37.78313, -122.46623,    4.     ])

In [9]:
import tensorflow as tf
from keras.utils import to_categorical

Using TensorFlow backend.


In [7]:
y_price_temp[5][0]

'$$$'

In [11]:
m = len(y_price_temp)
empty = np.empty(m)
for i in range(m):
    empty[i] = len(y_price_temp[i][0])
y_price = empty
y_price = to_categorical(y_price)
y_price

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [12]:
y_price = y_price[:, 1:]
size = y_price.shape[1]
size

4

In [16]:
y_price

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]], dtype=float32)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_price, random_state=1)

from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
from keras.models import Sequential

model = Sequential()
from keras.layers import Dense
model.add(Dense(units=4, activation='relu', input_dim=3))
model.add(Dense(units=5, activation='relu'))
model.add(Dense(units=size, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(
    X_train_scaled,
    y_train,
    epochs=150,
    shuffle=True,
    verbose=2
)

Epoch 1/150
 - 0s - loss: 1.3405 - accuracy: 0.4842
Epoch 2/150
 - 0s - loss: 1.2974 - accuracy: 0.6000
Epoch 3/150
 - 0s - loss: 1.2577 - accuracy: 0.6361
Epoch 4/150
 - 0s - loss: 1.2218 - accuracy: 0.6857
Epoch 5/150
 - 0s - loss: 1.1878 - accuracy: 0.7083
Epoch 6/150
 - 0s - loss: 1.1566 - accuracy: 0.7173
Epoch 7/150
 - 0s - loss: 1.1270 - accuracy: 0.7308
Epoch 8/150
 - 0s - loss: 1.0997 - accuracy: 0.7323
Epoch 9/150
 - 0s - loss: 1.0742 - accuracy: 0.7323
Epoch 10/150
 - 0s - loss: 1.0498 - accuracy: 0.7323
Epoch 11/150
 - 0s - loss: 1.0279 - accuracy: 0.7323
Epoch 12/150
 - 0s - loss: 1.0058 - accuracy: 0.7368
Epoch 13/150
 - 0s - loss: 0.9831 - accuracy: 0.7368
Epoch 14/150
 - 0s - loss: 0.9589 - accuracy: 0.7368
Epoch 15/150
 - 0s - loss: 0.9353 - accuracy: 0.7368
Epoch 16/150
 - 0s - loss: 0.9143 - accuracy: 0.7368
Epoch 17/150
 - 0s - loss: 0.8969 - accuracy: 0.7368
Epoch 18/150
 - 0s - loss: 0.8830 - accuracy: 0.7368
Epoch 19/150
 - 0s - loss: 0.8708 - accuracy: 0.7368
Ep

In [14]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(
    f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Deep Neural Network - Loss: 0.8372505715301445, Accuracy: 0.7117117047309875


In [15]:
print(model.predict(X_train_scaled[[1]]).round(2))
print(model.predict(X_train_scaled[[6]]).round(2))
print(model.predict(X_train_scaled[[10]]).round(2))
print(model.predict(X_train_scaled[[25]]).round(2))
print(model.predict(X_train_scaled[[30]]).round(2))
print(model.predict(X_train_scaled[[40]]).round(2))
print(model.predict(X_train_scaled[[50]]).round(2))
print(model.predict(X_train_scaled[[65]]).round(2))
print(model.predict(X_train_scaled[[85]]).round(2))

[[0.09 0.76 0.14 0.01]]
[[0.03 0.88 0.09 0.  ]]
[[0.07 0.69 0.17 0.07]]
[[0.07 0.71 0.17 0.05]]
[[0.06 0.82 0.12 0.  ]]
[[0.07 0.69 0.16 0.07]]
[[0.14 0.63 0.17 0.06]]
[[0.08 0.81 0.11 0.  ]]
[[0.05 0.82 0.13 0.01]]


In [16]:
# X_train_scaled[0]

In [17]:
# y_test